services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=http://${CONSOLE_DOMAIN}
      - MINIO_SERVER_URL=http://${API_DOMAIN}
    volumes:
      - minio-data:/data

volumes:
  minio-data:
