package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/slipwaydev/slipway/internal/core"
	"github.com/slipwaydev/slipway/internal/traefik"
)

// OverrideFile is the name of the generated override, written next to the
// app's compose file and passed as a second -f.
const OverrideFile = "slipway.override.yml"

// Override renders the compose override that exposes one stack service on the
// app's domain. Instead of rewriting the user's compose file (Dokploy's
// approach), Outhaul layers a second file over it:
//
//   - the exposed service joins the shared Traefik network — plus the stack's
//     implicit "default" network, restated because an explicit networks list
//     would otherwise replace it and cut the service off from its siblings;
//   - the service gets the standard Traefik labels (compose merges label maps,
//     so user labels survive), plus traefik.docker.network so Traefik routes
//     to the service's IP on the shared network, not its stack-internal one.
//
// The structure is three fixed levels deep, so it is rendered directly — no
// YAML dependency. All user-influenced values go through quoteYAML.
func Override(app core.App, network string, tlsEnabled bool) []byte {
	labels := traefik.Labels(app, app.ComposePort, tlsEnabled)
	labels["traefik.docker.network"] = network

	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by Outhaul on every deploy — do not edit.\n")
	b.WriteString("# Exposes one service on the app's domain via the shared Traefik network.\n")
	b.WriteString("services:\n")
	fmt.Fprintf(&b, "  %s:\n", quoteYAML(app.ComposeService))
	b.WriteString("    networks:\n")
	b.WriteString("      default: {}\n")
	fmt.Fprintf(&b, "      %s: {}\n", quoteYAML(network))
	b.WriteString("    labels:\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "      %s: %s\n", quoteYAML(k), quoteYAML(labels[k]))
	}
	b.WriteString("networks:\n")
	fmt.Fprintf(&b, "  %s:\n", quoteYAML(network))
	b.WriteString("    external: true\n")
	return []byte(b.String())
}

// quoteYAML renders s as a double-quoted YAML scalar. Backslash and double
// quote are the only characters needing escapes for the values we emit
// (domains, label keys, Traefik rules with backticks).
func quoteYAML(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
