package compose

import (
	"fmt"
	"sort"
	"strings"

	"github.com/slipwaydev/slipway/internal/core"
	"github.com/slipwaydev/slipway/internal/traefik"
)

// OverrideFile is the name of the generated override, written next to the
// app's compose file and passed as a second -f.
const OverrideFile = "slipway.override.yml"

// Override renders the compose override that publishes stack services on
// their configured domains. Instead of rewriting the user's compose file
// (Dokploy's approach), Outhaul layers a second file over it:
//
//   - each published service joins the shared Traefik network — plus the
//     stack's implicit "default" network, restated because an explicit
//     networks list would otherwise replace it and cut the service off from
//     its siblings;
//   - each service gets one Traefik router per domain pointing at it (compose
//     merges label maps, so user labels survive), plus traefik.docker.network
//     so Traefik routes to the service's IP on the shared network, not its
//     stack-internal one. Router names are namespaced by the domain row ID,
//     keeping them unique across apps and stable across deploys.
//
// The structure is three fixed levels deep, so it is rendered directly — no
// YAML dependency. All user-influenced values go through quoteYAML.
func Override(app core.App, domains []core.ComposeDomain, network string, tlsEnabled bool) []byte {
	byService := map[string][]core.ComposeDomain{}
	var services []string
	for _, d := range domains {
		if _, seen := byService[d.Service]; !seen {
			services = append(services, d.Service)
		}
		byService[d.Service] = append(byService[d.Service], d)
	}
	sort.Strings(services)

	var b strings.Builder
	b.WriteString("# Generated by Outhaul on every deploy — do not edit.\n")
	b.WriteString("# Publishes stack services on their domains via the shared Traefik network.\n")
	b.WriteString("services:\n")
	for _, svc := range services {
		labels := map[string]string{
			"traefik.enable":         "true",
			"slipway.managed":        "true",
			"slipway.app":            app.Name,
			"traefik.docker.network": network,
		}
		for _, d := range byService[svc] {
			for k, v := range traefik.RouteLabels(domainRouter(app.Name, d.ID), d.Domain, d.Port, tlsEnabled) {
				labels[k] = v
			}
		}
		keys := make([]string, 0, len(labels))
		for k := range labels {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		fmt.Fprintf(&b, "  %s:\n", quoteYAML(svc))
		b.WriteString("    networks:\n")
		b.WriteString("      default: {}\n")
		fmt.Fprintf(&b, "      %s: {}\n", quoteYAML(network))
		b.WriteString("    labels:\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "      %s: %s\n", quoteYAML(k), quoteYAML(labels[k]))
		}
	}
	b.WriteString("networks:\n")
	fmt.Fprintf(&b, "  %s:\n", quoteYAML(network))
	b.WriteString("    external: true\n")
	return []byte(b.String())
}

// domainRouter names the Traefik router for one compose domain.
func domainRouter(appName string, domainID int64) string {
	return fmt.Sprintf("slipway-%s-d%d", appName, domainID)
}

// quoteYAML renders s as a double-quoted YAML scalar. Backslash and double
// quote are the only characters needing escapes for the values we emit
// (domains, label keys, Traefik rules with backticks).
func quoteYAML(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
