#!/usr/bin/env sh
# Outhaul remote installer. Served at https://outhaul.sh/install.
# Usage: curl -fsSL https://outhaul.sh/install | sh
# Runs under Debian's dash — keep it POSIX, no bashisms.
set -eu

OUTHAUL_REPO="${OUTHAUL_REPO:-https://github.com/outhaul-dev/outhaul.git}"

# ------------------------------------------------------------------ helpers --

# Prints the concrete Go version to download (e.g. 1.26.4). Prefers the
# `toolchain goX.Y.Z` directive; falls back to the `go X.Y[.Z]` directive.
go_version_from_gomod() {
	f=${1:-go.mod}
	v=$(awk '/^toolchain[ \t]+go[0-9]/ { sub(/^go/,"",$2); print $2; exit }' "$f")
	[ -n "$v" ] || v=$(awk '/^go[ \t]+[0-9]/ { print $2; exit }' "$f")
	printf '%s\n' "$v"
}

# Pure: decide color level from explicit inputs (testable).
# 0=plain 1=16-color 2=256-color 3=truecolor
_color_level() { # no_color is_tty colorterm tput_colors
	[ -n "$1" ] && { echo 0; return; }
	[ "$2" != 1 ] && { echo 0; return; }
	case "$3" in *truecolor*|*24bit*) echo 3; return;; esac
	if [ "${4:-0}" -ge 256 ]; then echo 2
	elif [ "${4:-0}" -ge 8 ]; then echo 1
	else echo 0; fi
}

# Gathers the real environment and calls _color_level.
detect_color_level() {
	tc=$(tput colors 2>/dev/null || echo 0)
	if [ -t 1 ]; then tty=1; else tty=0; fi
	_color_level "${NO_COLOR:-}" "$tty" "${COLORTERM:-}" "$tc"
}

# Prints the space-separated, sorted, de-duplicated port set to open.
# SSH (22) is ALWAYS included. Mode a adds 80/443. A non-empty git port is added.
derive_firewall_ports() { # mode gitport
	mode=$1; gitport=${2:-}
	set -- 22
	[ "$mode" = a ] && set -- "$@" 80 443
	[ -n "$gitport" ] && set -- "$@" "$gitport"
	printf '%s\n' "$@" | sort -n -u | paste -sd' ' -
}

# Returns success (0) when total RAM+swap is below 2 GiB and a build
# swapfile should be offered. Inputs are in KiB (as /proc/meminfo reports).
need_swap() { # mem_kb swap_kb
	total=$(( ${1:-0} + ${2:-0} ))
	[ "$total" -lt 2097152 ]
}

# Writes /etc/outhaul.env from wizard answers. Mode a includes the public
# URL + ACME email (enables HTTPS on first boot); other modes omit them.
# Comments go on their OWN line — systemd keeps an inline "# ..." as part of
# the value, which would corrupt e.g. the email.
write_env_file() { # dest mode url email sshaddr
	dest=$1 mode=$2 url=$3 email=$4 sshaddr=$5
	{
		printf '# Outhaul configuration — generated by the installer.\n'
		printf '# OUTHAUL_* overrides, one per line. Comments on their OWN line.\n'
		printf '# Edit, then: systemctl restart outhaul\n\n'
		if [ "$mode" = a ]; then
			printf 'OUTHAUL_PUBLIC_URL=%s\n' "$url"
			printf 'OUTHAUL_ACME_EMAIL=%s\n' "$email"
		fi
		[ -n "$sshaddr" ] && printf 'OUTHAUL_SSH_ADDR=%s\n' "$sshaddr"
	} > "$dest"
	chmod 0600 "$dest"
}

# Yes/no prompt read from fd 3. $2 is the default ('y' or 'n').
ask_yes_no() { # prompt default
	_p=$1; _d=$2
	if [ "$_d" = y ]; then _h='Y/n'; else _h='y/N'; fi
	printf '%s [%s] ' "$_p" "$_h" >&2
	read _a <&3 2>/dev/null || _a=''
	[ -z "$_a" ] && _a=$_d
	case "$_a" in [Yy]*) return 0;; *) return 1;; esac
}

# Free-text prompt read from fd 3; prints the answer (or default) to stdout.
ask_value() { # prompt default
	_p=$1; _d=$2
	if [ -n "$_d" ]; then printf '%s [%s] ' "$_p" "$_d" >&2; else printf '%s ' "$_p" >&2; fi
	read _a <&3 2>/dev/null || _a=''
	[ -z "$_a" ] && _a=$_d
	printf '%s\n' "$_a"
}

main() {
	printf 'outhaul installer\n'
}

# Run main only when executed, not when sourced by the test suite.
if [ "${OUTHAUL_INSTALLER_LIB:-0}" != 1 ]; then
	main "$@"
fi
