#!/usr/bin/env sh
# Outhaul remote installer. Served at https://outhaul.sh/install.
# Usage: curl -fsSL https://outhaul.sh/install | sh
# Runs under Debian's dash — keep it POSIX, no bashisms.
set -eu

OUTHAUL_REPO="${OUTHAUL_REPO:-https://github.com/outhaul-dev/outhaul.git}"

# ------------------------------------------------------------------ helpers --

# Prints the concrete Go version to download (e.g. 1.26.4). Prefers the
# `toolchain goX.Y.Z` directive; falls back to the `go X.Y[.Z]` directive.
go_version_from_gomod() {
	f=${1:-go.mod}
	v=$(awk '/^toolchain[ \t]+go[0-9]/ { sub(/^go/,"",$2); print $2; exit }' "$f")
	[ -n "$v" ] || v=$(awk '/^go[ \t]+[0-9]/ { print $2; exit }' "$f")
	printf '%s\n' "$v"
}

# Pure: decide color level from explicit inputs (testable).
# 0=plain 1=16-color 2=256-color 3=truecolor
_color_level() { # no_color is_tty colorterm tput_colors
	[ -n "$1" ] && { echo 0; return; }
	[ "$2" != 1 ] && { echo 0; return; }
	case "$3" in *truecolor*|*24bit*) echo 3; return;; esac
	if [ "${4:-0}" -ge 256 ]; then echo 2
	elif [ "${4:-0}" -ge 8 ]; then echo 1
	else echo 0; fi
}

# Gathers the real environment and calls _color_level.
detect_color_level() {
	tc=$(tput colors 2>/dev/null || echo 0)
	if [ -t 1 ]; then tty=1; else tty=0; fi
	_color_level "${NO_COLOR:-}" "$tty" "${COLORTERM:-}" "$tc"
}

# Prints the space-separated, sorted, de-duplicated port set to open.
# SSH (22) is ALWAYS included. Mode a adds 80/443. A non-empty git port is added.
derive_firewall_ports() { # mode gitport
	mode=$1; gitport=${2:-}
	set -- 22
	[ "$mode" = a ] && set -- "$@" 80 443
	[ -n "$gitport" ] && set -- "$@" "$gitport"
	printf '%s\n' "$@" | sort -n -u | paste -sd' ' -
}

# Returns success (0) when total RAM+swap is below 2 GiB and a build
# swapfile should be offered. Inputs are in KiB (as /proc/meminfo reports).
need_swap() { # mem_kb swap_kb
	total=$(( ${1:-0} + ${2:-0} ))
	[ "$total" -lt 2097152 ]
}

# Writes /etc/outhaul.env from wizard answers. Mode a includes the public
# URL + ACME email (enables HTTPS on first boot); other modes omit them.
# Comments go on their OWN line — systemd keeps an inline "# ..." as part of
# the value, which would corrupt e.g. the email.
write_env_file() { # dest mode url email sshaddr
	dest=$1 mode=$2 url=$3 email=$4 sshaddr=$5
	{
		printf '# Outhaul configuration — generated by the installer.\n'
		printf '# OUTHAUL_* overrides, one per line. Comments on their OWN line.\n'
		printf '# Edit, then: systemctl restart outhaul\n\n'
		if [ "$mode" = a ]; then
			printf 'OUTHAUL_PUBLIC_URL=%s\n' "$url"
			printf 'OUTHAUL_ACME_EMAIL=%s\n' "$email"
		fi
		[ -n "$sshaddr" ] && printf 'OUTHAUL_SSH_ADDR=%s\n' "$sshaddr"
	} > "$dest"
	chmod 0600 "$dest"
}

# Yes/no prompt read from fd 3. $2 is the default ('y' or 'n').
ask_yes_no() { # prompt default
	_p=$1; _d=$2
	if [ "$_d" = y ]; then _h='Y/n'; else _h='y/N'; fi
	printf '%s [%s] ' "$_p" "$_h" >&2
	read _a <&3 2>/dev/null || _a=''
	[ -z "$_a" ] && _a=$_d
	case "$_a" in [Yy]*) return 0;; *) return 1;; esac
}

# Free-text prompt read from fd 3; prints the answer (or default) to stdout.
ask_value() { # prompt default
	_p=$1; _d=$2
	if [ -n "$_d" ]; then printf '%s [%s] ' "$_p" "$_d" >&2; else printf '%s ' "$_p" >&2; fi
	read _a <&3 2>/dev/null || _a=''
	[ -z "$_a" ] && _a=$_d
	printf '%s\n' "$_a"
}

# ------------------------------------------------------------------- ui --

# Sets COLOR, UNICODE, WIDTH globals. Call once at startup.
init_ui() {
	COLOR=$(detect_color_level)
	case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in *[Uu][Tt][Ff]-8*|*[Uu][Tt][Ff]8*) UNICODE=1;; *) UNICODE=0;; esac
	[ "$COLOR" = 0 ] && UNICODE=0
	WIDTH=$(tput cols 2>/dev/null || echo 80)
	[ -n "$WIDTH" ] || WIDTH=80
}

# Apply an RGB (truecolor) / bold-magenta (16+) / plain color to text.
paint() { # r g b text...
	_r=$1; _g=$2; _b=$3; shift 3
	if [ "${COLOR:-0}" -ge 3 ]; then printf '\033[38;2;%d;%d;%dm%s\033[0m' "$_r" "$_g" "$_b" "$*"
	elif [ "${COLOR:-0}" -ge 1 ]; then printf '\033[1;35m%s\033[0m' "$*"
	else printf '%s' "$*"; fi
}

_c() { # color-code-or-plain: emit ANSI SGR $1 only when COLOR>=1
	[ "${COLOR:-0}" -ge 1 ] && printf '\033[%sm' "$1" || true
}

hr() {
	[ "${UNICODE:-0}" = 1 ] && ch='─' || ch='-'
	i=0; line=''
	while [ "$i" -lt "$((WIDTH<80?WIDTH:60))" ]; do line="$line$ch"; i=$((i+1)); done
	_c 90; printf '%s' "$line"; _c 0; printf '\n'
}

step_ok()   { [ "${UNICODE:-0}" = 1 ] && m='✔' || m='+'; _c '1;32'; printf '  %s ' "$m"; _c 0; printf '%s\n' "$1"; }
step_fail() { [ "${UNICODE:-0}" = 1 ] && m='✖' || m='x'; _c '1;31'; printf '  %s ' "$m"; _c 0; printf '%s\n' "$1"; }
note()      { _c 90; printf '    %s\n' "$1"; _c 0; }

# Raw log mirror (Task 20 wires LOGFILE); safe if unset.
log_line() { [ -n "${LOGFILE:-}" ] && printf '%s\n' "$*" >> "$LOGFILE" 2>/dev/null || true; }

die() { _c '1;31'; printf 'error: ' >&2; _c 0; printf '%s\n' "$1" >&2; log_line "ERROR: $1"; exit 1; }

_hero_rgb() { case $1 in
	1) echo 247 120 186;; 2) echo 188 140 255;;
	3) echo 88 166 255;;  4) echo 63 185 80;; esac; }

# Gradient ASCII wordmark; degrades to a single line when narrow or plain.
hero() {
	if [ "${WIDTH:-80}" -lt 62 ]; then
		printf '\n'; _c '1;35'; printf '  Outhaul'; _c 0; printf ' — self-hosted PaaS\n\n'; return
	fi
	printf '\n'
	set -- \
'  ██████  ██    ██ ████████ ██   ██  █████  ██    ██ ██     ' \
'  ██   ██ ██    ██    ██    ██   ██ ██   ██ ██    ██ ██     ' \
'  ██   ██ ██    ██    ██    ███████ ███████ ██    ██ ██     ' \
'  ██████   ██████     ██    ██   ██ ██   ██  ██████  ███████'
	i=0
	# shellcheck disable=SC2046 # intentional: _hero_rgb's 3 numbers become 3 args to paint
	for line in "$@"; do i=$((i+1)); paint $(_hero_rgb "$i") "$line"; printf '\n'; done
	_c 90; printf '   self-hosted PaaS · one binary, zero sprawl\n'; _c 0; printf '\n'
}

# Braille spinner on a background PID while a long step runs.
# Usage: spinner_start "message"; <work>; spinner_stop 0|1
SPIN_PID=''
spinner_start() {
	SPIN_MSG=$1
	if [ "${COLOR:-0}" = 0 ] || [ ! -t 1 ]; then printf '  .. %s\n' "$SPIN_MSG"; return; fi
	( frames='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'; [ "${UNICODE:-0}" = 1 ] || frames='|/-\\'
	  while :; do
		i=1
		while [ "$i" -le ${#frames} ]; do
			f=$(printf '%s' "$frames" | cut -c "$i")
			printf '\r  \033[35m%s\033[0m %s' "$f" "$SPIN_MSG"
			sleep 0.1; i=$((i+1))
		done
	  done ) &
	SPIN_PID=$!
}
spinner_stop() { # exitcode
	[ -n "${SPIN_PID:-}" ] && kill "$SPIN_PID" 2>/dev/null && wait "$SPIN_PID" 2>/dev/null
	SPIN_PID=''
	[ "${COLOR:-0}" = 0 ] && return 0
	printf '\r\033[K'
	if [ "${1:-0}" -eq 0 ]; then step_ok "$SPIN_MSG"; else step_fail "$SPIN_MSG"; fi
}

# A single-line gradient progress bar: progress_bar PERCENT LABEL
progress_bar() { # percent label
	pct=$1; label=${2:-}
	width=30; filled=$(( pct * width / 100 ))
	[ "$filled" -gt "$width" ] && filled=$width
	bar=''; i=0
	while [ "$i" -lt "$filled" ]; do bar="$bar#"; i=$((i+1)); done
	while [ "$i" -lt "$width" ]; do bar="$bar."; i=$((i+1)); done
	if [ "${COLOR:-0}" -ge 1 ]; then
		printf '\r  \033[32m%s\033[0m %3d%% %s' "$bar" "$pct" "$label"
	else
		printf '\r  %s %3d%% %s' "$bar" "$pct" "$label"
	fi
}

# ------------------------------------------------------------------ system --

# Prints the numeric KiB value for a /proc/meminfo key (default file /proc/meminfo).
read_meminfo_kb() { # key file?
	awk -v k="$1:" '$1==k {print $2; exit}' "${2:-/proc/meminfo}"
}

# Prints the distro ID from an os-release file (default /etc/os-release).
detect_distro() { # file?
	awk -F= '$1=="ID"{gsub(/"/,"",$2); print $2; exit}' "${1:-/etc/os-release}"
}

# Full preflight. Aborts on hard failures; warns (via fd 3 confirm) on soft ones.
preflight() {
	[ "$(id -u)" -eq 0 ] || die "run as root (curl -fsSL https://outhaul.sh/install | sudo sh)"
	command -v systemctl >/dev/null 2>&1 || die "systemd is required (no systemctl found)"
	distro=$(detect_distro)
	if [ "$distro" != debian ]; then
		step_fail "unsupported distro: ${distro:-unknown} (V1 targets Debian)"
		ask_yes_no "  Continue anyway?" n || die "aborted on unsupported distro"
	else
		step_ok "Debian detected"
	fi
	arch=$(uname -m)
	case "$arch" in x86_64|amd64|aarch64|arm64) step_ok "architecture $arch";;
		*) die "unsupported architecture: $arch";; esac
	MEM_KB=$(read_meminfo_kb MemTotal); SWAP_KB=$(read_meminfo_kb SwapTotal)
	note "memory: $((MEM_KB/1024)) MB RAM, $((SWAP_KB/1024)) MB swap"
}

ensure_docker() {
	if command -v docker >/dev/null 2>&1; then step_ok "Docker present"; else
		spinner_start "installing Docker (get.docker.com)"
		# set +e so a failed install still reaches spinner_stop + die (see build_binary note).
		set +e; curl -fsSL https://get.docker.com | sh >>"${LOGFILE:-/dev/null}" 2>&1; rc=$?; set -e
		spinner_stop "$rc"
		[ "$rc" -eq 0 ] || die "Docker install failed — see ${LOGFILE:-the install log}"
	fi
	systemctl enable --now docker >/dev/null 2>&1 || true
	docker compose version >/dev/null 2>&1 || die "docker compose v2 plugin missing (install docker-compose-plugin)"
	step_ok "docker compose v2 available"
}

ensure_git() {
	if command -v git >/dev/null 2>&1; then step_ok "git present"; return; fi
	spinner_start "installing git"
	set +e; { apt-get update -qq && apt-get install -y -qq git; } >>"${LOGFILE:-/dev/null}" 2>&1; rc=$?; set -e
	spinner_stop "$rc"
	[ "$rc" -eq 0 ] || die "git install failed — see ${LOGFILE:-the install log}"
}

# Optional — caller gates on ask_yes_no.
ensure_nixpacks() {
	if command -v nixpacks >/dev/null 2>&1; then step_ok "nixpacks present"; return; fi
	spinner_start "installing nixpacks"
	set +e; curl -fsSL https://nixpacks.com/install.sh | bash >>"${LOGFILE:-/dev/null}" 2>&1; rc=$?; set -e
	spinner_stop "$rc"
	# Optional: a failure is not fatal — Dockerfile/compose apps still deploy.
	[ "$rc" -eq 0 ] || note "nixpacks install failed — you can retry later; Dockerfile/compose apps work without it"
}

# Maps uname -m to the go.dev download arch token.
go_dl_arch() { # uname_m
	case "$1" in
		x86_64|amd64)  echo amd64;;
		aarch64|arm64) echo arm64;;
		*) return 1;;
	esac
}

# Downloads the go.mod-pinned Go toolchain to a temp dir, verifies its SHA256
# against the value published in the accompanying .sha256, and exports PATH.
# Sets GOROOT_TMP so the caller can remove it later.
install_go_toolchain() { # version
	ver=$1
	if command -v go >/dev/null 2>&1 && [ "$(go env GOVERSION 2>/dev/null)" = "go$ver" ]; then
		step_ok "Go $ver present"; return
	fi
	a=$(go_dl_arch "$(uname -m)") || die "unsupported arch for Go download"
	GOROOT_TMP=$(mktemp -d)
	tarball="go${ver}.linux-${a}.tar.gz"
	url="https://go.dev/dl/${tarball}"
	spinner_start "downloading Go $ver ($a)"
	set +e
	{
		curl -fsSL "$url" -o "$GOROOT_TMP/$tarball" &&
		curl -fsSL "$url.sha256" -o "$GOROOT_TMP/$tarball.sha256"
	} >>"${LOGFILE:-/dev/null}" 2>&1
	rc=$?
	set -e
	spinner_stop "$rc"; [ "$rc" -eq 0 ] || die "could not download Go $ver from $url"
	sum=$(cat "$GOROOT_TMP/$tarball.sha256")
	echo "$sum  $GOROOT_TMP/$tarball" | sha256sum -c - >>"${LOGFILE:-/dev/null}" 2>&1 \
		|| die "Go toolchain checksum mismatch — refusing to build"
	step_ok "Go $ver checksum verified"
	tar -C "$GOROOT_TMP" -xzf "$GOROOT_TMP/$tarball"
	PATH="$GOROOT_TMP/go/bin:$PATH"; export PATH
	GOTOOLCHAIN=local; export GOTOOLCHAIN   # do not let go fetch a different one
	step_ok "Go $ver ready"
}

BUILD_SWAP=/var/lib/outhaul-build.swap

# Offers a temporary build swapfile when RAM+swap is under 2 GiB.
maybe_add_swap() { # mem_kb swap_kb
	need_swap "$1" "$2" || return 0
	note "low memory — the Go build may be OOM-killed without extra swap"
	ask_yes_no "  Create a temporary 2 GB swapfile for the build?" y || return 0
	[ -e "$BUILD_SWAP" ] && return 0
	spinner_start "creating build swapfile"
	# Mark now so cleanup removes the file even if swapon fails partway through.
	SWAP_ADDED=1
	set +e
	{
		fallocate -l 2G "$BUILD_SWAP" 2>/dev/null || dd if=/dev/zero of="$BUILD_SWAP" bs=1M count=2048
		chmod 600 "$BUILD_SWAP" && mkswap "$BUILD_SWAP" && swapon "$BUILD_SWAP"
	} >>"${LOGFILE:-/dev/null}" 2>&1
	rc=$?
	set -e
	spinner_stop "$rc"
	# Not fatal: continue even if swap couldn't be enabled (the build may just be tight).
	[ "$rc" -eq 0 ] || note "could not enable build swap — continuing without it"
}

# Removes only the swapfile we created.
remove_build_swap() {
	[ "${SWAP_ADDED:-0}" = 1 ] || return 0
	swapoff "$BUILD_SWAP" 2>/dev/null || true
	rm -f "$BUILD_SWAP"
	SWAP_ADDED=0
}

# Clones the repo (or uses --from-checkout dir). Prints the source dir via SRC_DIR.
fetch_source() {
	if [ "${FROM_CHECKOUT:-0}" = 1 ]; then
		SRC_DIR=$(cd "$CHECKOUT_DIR" && pwd)
		[ -f "$SRC_DIR/go.mod" ] || die "--from-checkout: no go.mod in $SRC_DIR"
		step_ok "using local checkout $SRC_DIR"
		return
	fi
	SRC_DIR=$(mktemp -d)
	spinner_start "cloning outhaul"
	set +e; git clone --depth 1 "$OUTHAUL_REPO" "$SRC_DIR" >>"${LOGFILE:-/dev/null}" 2>&1; rc=$?; set -e
	spinner_stop "$rc"
	[ "$rc" -eq 0 ] || die "could not clone $OUTHAUL_REPO — see ${LOGFILE:-the install log}"
}

# Builds ./outhaul in SRC_DIR. Streams go build output to the log; shows a
# spinner (progress bar is best-effort since `go build` has no clean %).
build_binary() {
	# spinner_start runs in THIS shell (not the subshell) so cleanup can see SPIN_PID,
	# and set +e keeps a failed build from aborting before spinner_stop + die.
	spinner_start "building outhaul (this can take a few minutes)"
	set +e
	( cd "$SRC_DIR" && GOFLAGS=-buildvcs=false go build -o outhaul . ) >>"${LOGFILE:-/dev/null}" 2>&1
	rc=$?
	set -e
	spinner_stop "$rc"
	{ [ "$rc" -eq 0 ] && [ -x "$SRC_DIR/outhaul" ]; } || die "build failed — see ${LOGFILE:-the install log}"
	step_ok "binary built"
}

# Pure: does PUBLIC_IP appear in the resolved-IP set?
domain_ip_matches() { # public_ip resolved_ips
	pub=$1
	# shellcheck disable=SC2086 # intentional word-splitting of the resolved-IP set into positional args
	set -- $2
	[ "$#" -gt 0 ] || return 1
	for ip in "$@"; do [ "$ip" = "$pub" ] && return 0; done
	return 1
}

host_public_ip() {
	curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null ||
	curl -fsS --max-time 5 https://ifconfig.me 2>/dev/null || true
}

# Space-separated A records for a name, using whatever resolver tool exists.
resolve_a() { # name
	if command -v getent >/dev/null 2>&1; then
		getent ahostsv4 "$1" 2>/dev/null | awk '{print $1}' | sort -u | paste -sd' ' -
	else
		host "$1" 2>/dev/null | awk '/has address/{print $NF}' | paste -sd' ' -
	fi
}

port_in_use() { # port
	if command -v ss >/dev/null 2>&1; then ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]$1\$"
	else netstat -ltn 2>/dev/null | awk '{print $4}' | grep -qE "[:.]$1\$"; fi
}

# Warns (does not hard-fail) about DNS/port issues before choosing ACME.
acme_preflight() { # domain
	dom=$1
	pub=$(host_public_ip)
	ips=$(resolve_a "$dom")
	note "this server's public IP: ${pub:-unknown}"
	note "$dom resolves to: ${ips:-<nothing>}"
	if [ -n "$pub" ] && ! domain_ip_matches "$pub" "$ips"; then
		step_fail "$dom does not point at this server"
		note "create a DNS A record:  $dom  A  $pub"
		ask_yes_no "  Continue with Let's Encrypt anyway?" n ||
			die "fix DNS, then re-run the installer"
	else
		step_ok "$dom points at this server"
	fi
	for p in 80 443; do
		port_in_use "$p" && step_fail "port $p already in use — Traefik may fail to bind" || true
	done
}

# Opens the given port set with ufw. CRITICAL: `ufw allow` every port
# (especially SSH/22) BEFORE `ufw enable`, so the running session survives.
apply_firewall() { # ports (space separated, must include 22)
	ports=$1
	if ! command -v ufw >/dev/null 2>&1; then
		spinner_start "installing ufw"
		set +e; { apt-get update -qq && apt-get install -y -qq ufw; } >>"${LOGFILE:-/dev/null}" 2>&1; rc=$?; set -e
		spinner_stop "$rc"
		# Not fatal: skip firewalling rather than abort the whole install.
		[ "$rc" -eq 0 ] || { note "could not install ufw — skipping firewall (open ports manually)"; return 0; }
	fi
	# shellcheck disable=SC2086 # intentional word-splitting of the space-separated port list
	for p in $ports; do
		ufw allow "$p"/tcp >>"${LOGFILE:-/dev/null}" 2>&1 || true
	done
	# --force avoids the interactive "proceed?" prompt; SSH is already allowed above.
	ufw --force enable >>"${LOGFILE:-/dev/null}" 2>&1 || true
	step_ok "firewall: opened $ports (SSH preserved)"
	note "open more later with: ufw allow <port>"
}

# Carry legacy slipway state across the rename (mirrors old install.sh).
migrate_slipway() {
	if [ -d /var/lib/slipway ] && [ ! -e /var/lib/outhaul ]; then
		systemctl stop outhaul 2>/dev/null || true
		mv /var/lib/slipway /var/lib/outhaul
		[ -f /var/lib/outhaul/slipway.db ] && mv /var/lib/outhaul/slipway.db /var/lib/outhaul/outhaul.db
		step_ok "migrated /var/lib/slipway -> /var/lib/outhaul"
	fi
	rm -f /usr/local/bin/slipway
}

ensure_service_user() {
	if ! id outhaul >/dev/null 2>&1; then
		nologin=$(command -v nologin || echo /usr/sbin/nologin)
		useradd --system --home-dir /var/lib/outhaul --create-home --shell "$nologin" outhaul
		step_ok "created system user outhaul"
	fi
	usermod -aG docker outhaul
}

install_binary() {
	install -m 0755 "$SRC_DIR/outhaul" /usr/local/bin/outhaul
	step_ok "installed /usr/local/bin/outhaul"
}

# Installs the systemd unit shipped in the repo and (re)starts the service.
install_service() {
	install -m 0644 "$SRC_DIR/deploy/outhaul.service" /etc/systemd/system/outhaul.service
	systemctl daemon-reload
	if systemctl is-active --quiet outhaul; then systemctl restart outhaul
	else systemctl enable --now outhaul; fi
	step_ok "outhaul service started"
}

# Local admin URL to probe. Accepts OUTHAUL_LISTEN_ADDR-style ":8080".
admin_health_url() { # listen_addr
	addr=${1:-:8080}; [ -n "$addr" ] || addr=:8080
	port=${addr##*:}
	printf 'http://127.0.0.1:%s/\n' "$port"
}

# Extracts the one-time setup URL from a stream of journald lines.
# Matches the binary's "open: http://HOST:PORT/setup?token=TOKEN" hint.
extract_setup_url() {
	grep -oE 'https?://[^ ]+/setup\?token=[A-Za-z0-9_-]+' | head -1
}

# Polls the admin endpoint up to ~30s. Returns 0 when it answers with ANY
# HTTP response (no -f: a pre-setup redirect/403 still means "reachable").
wait_healthy() { # url
	url=$1; i=0
	spinner_start "waiting for outhaul to answer"
	while [ "$i" -lt 30 ]; do
		if curl -sS --max-time 2 -o /dev/null "$url" 2>/dev/null; then spinner_stop 0; return 0; fi
		sleep 1; i=$((i+1))
	done
	spinner_stop 1; return 1
}

# Final boxed summary + confetti. Args passed as positional data.
completion_screen() { # mode url ports setup_url healthy(0/1)
	mode=$1; url=$2; ports=$3; setup=$4; healthy=$5
	printf '\n'; hr
	_c '1;32'; printf '  Outhaul is installed\n'; _c 0
	[ "$healthy" = 0 ] && step_ok "admin UI reachable" || step_fail "admin UI did not answer yet (check: journalctl -u outhaul)"
	[ -n "$ports" ] && note "firewall: $ports open"
	case "$mode" in
		a) note "HTTPS: Let's Encrypt configured for $url";;
		b) _c '1;33'; printf '  → Finish Cloudflare Tunnel: log in, then paste your connector token in Settings → Tunnel\n'; _c 0;;
		c) note "admin UI on :8080 — set OUTHAUL_PUBLIC_URL + OUTHAUL_ACME_EMAIL later for HTTPS";;
	esac
	if [ -n "$setup" ]; then
		printf '\n  Open this one-time setup URL to create your admin account:\n'
		_c '1;36'; printf '    %s\n' "$setup"; _c 0
	else
		note "find the setup URL with: journalctl -u outhaul | grep -i setup"
	fi
	# Confetti flourish (skipped in plain mode).
	if [ "${COLOR:-0}" -ge 1 ] && [ "${UNICODE:-0}" = 1 ]; then
		printf '\n  '; for s in '✦' '✧' '·' '✦' '✧' '·' '✦' '✧'; do printf '%s ' "$s"; done; printf '\n'
	fi
	hr
}

LOGFILE=/var/log/outhaul-install.log
VERBOSE=0
FROM_CHECKOUT=0
CHECKOUT_DIR=.

parse_args() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--verbose) VERBOSE=1;;
			--from-checkout) FROM_CHECKOUT=1; CHECKOUT_DIR=${2:-.}; shift;;
			-h|--help) printf 'usage: bootstrap.sh [--verbose] [--from-checkout DIR]\n'; exit 0;;
			*) die "unknown option: $1";;
		esac
		shift
	done
}

cleanup() {
	if [ -n "${SPIN_PID:-}" ]; then kill "$SPIN_PID" 2>/dev/null || true; fi
	remove_build_swap || true
	if [ "${FROM_CHECKOUT:-0}" != 1 ] && [ -n "${SRC_DIR:-}" ]; then rm -rf "$SRC_DIR"; fi
	if [ -n "${GOROOT_TMP:-}" ]; then rm -rf "$GOROOT_TMP"; fi
}

# Ingress-mode menu. Sets MODE (a/b/c), PUBLIC_URL, ACME_EMAIL.
choose_ingress() {
	printf '\n  How should apps be reachable?\n'
	printf '    1) Public domain + automatic HTTPS (Let'\''s Encrypt)\n'
	printf '    2) Cloudflare Tunnel (no public IP / ports needed)\n'
	printf '    3) Local only for now (admin UI on :8080)\n'
	choice=$(ask_value "  Choose 1/2/3:" 1)
	case "$choice" in
		2) MODE=b; PUBLIC_URL=''; ACME_EMAIL='';;
		3) MODE=c; PUBLIC_URL=''; ACME_EMAIL='';;
		*) MODE=a
		   PUBLIC_URL=$(ask_value "  Public URL (e.g. https://paas.example.com):" '')
		   dom=${PUBLIC_URL#*://}; dom=${dom%%/*}
		   acme_preflight "$dom"
		   ACME_EMAIL=$(ask_value "  Email for Let's Encrypt:" '');;
	esac
}

main() {
	parse_args "$@"
	: > "$LOGFILE" 2>/dev/null || LOGFILE=/dev/null
	if [ "$VERBOSE" = 1 ]; then LOGFILE=/dev/stderr; fi
	trap cleanup EXIT INT TERM
	# Open the controlling terminal on fd 3 for prompts. Under `curl | sh` there is
	# usually a real /dev/tty; if not (fully headless pipe), fall back to /dev/null
	# so prompts read EOF and take their safe defaults — never the script text on stdin.
	exec 3</dev/tty 2>/dev/null || exec 3</dev/null

	init_ui
	hero
	preflight

	choose_ingress

	GITPORT=$(ask_value "  Git-push-to-deploy port (blank to disable):" 2222)
	if [ -n "$GITPORT" ]; then SSH_ADDR=":$GITPORT"; else SSH_ADDR=''; fi

	if ask_yes_no "  Install Nixpacks (needed for auto-detected builds)?" y; then WANT_NIXPACKS=1; else WANT_NIXPACKS=0; fi
	if ask_yes_no "  Configure the firewall (ufw) now?" y; then WANT_FW=1; else WANT_FW=0; fi

	ensure_docker
	ensure_git
	if [ "$WANT_NIXPACKS" = 1 ]; then ensure_nixpacks; fi

	fetch_source
	GO_VER=$(go_version_from_gomod "$SRC_DIR/go.mod")
	maybe_add_swap "${MEM_KB:-0}" "${SWAP_KB:-0}"
	install_go_toolchain "$GO_VER"
	build_binary
	remove_build_swap

	migrate_slipway
	ensure_service_user
	install_binary
	if [ ! -f /etc/outhaul.env ]; then
		write_env_file /etc/outhaul.env "$MODE" "$PUBLIC_URL" "$ACME_EMAIL" "$SSH_ADDR"
		step_ok "wrote /etc/outhaul.env"
	else
		note "/etc/outhaul.env exists — left unchanged"
	fi
	install_service

	if [ -n "${GOROOT_TMP:-}" ]; then
		if ask_yes_no "  Remove the downloaded Go toolchain (~150 MB)?" y; then
			rm -rf "$GOROOT_TMP"; GOROOT_TMP=''; step_ok "removed Go toolchain"
		fi
	fi

	PORTS=''
	if [ "$WANT_FW" = 1 ]; then
		PORTS=$(derive_firewall_ports "$MODE" "$GITPORT")
		# Preserve the port of the admin's LIVE SSH session too, in case sshd
		# listens somewhere other than 22 — otherwise enabling ufw locks them out.
		if [ -n "${SSH_CONNECTION:-}" ]; then
			assh=${SSH_CONNECTION##* }
			case " $PORTS " in *" $assh "*) ;; *) [ -n "$assh" ] && PORTS="$PORTS $assh";; esac
		fi
		printf '  Firewall will open (SSH always preserved): %s\n' "$PORTS"
		if ask_yes_no "  Proceed?" y; then apply_firewall "$PORTS"; else PORTS=''; fi
	fi

	HURL=$(admin_health_url "${OUTHAUL_LISTEN_ADDR:-:8080}")
	if wait_healthy "$HURL"; then HEALTHY=0; else HEALTHY=1; fi
	# -b: current boot only, so a re-run doesn't surface a stale first-boot token.
	SETUP=$(journalctl -u outhaul -b --no-pager 2>/dev/null | extract_setup_url)

	completion_screen "$MODE" "$PUBLIC_URL" "$PORTS" "$SETUP" "$HEALTHY"
}

# Run main only when executed, not when sourced by the test suite.
if [ "${OUTHAUL_INSTALLER_LIB:-0}" != 1 ]; then
	main "$@"
fi
